### ISSUE TITLE
Sample State and Routes Design Docs Review

### ISSUE THREAD

**Issue by rlim92** [nyan9/TumblyTube#2]
Hey Ryan! Design docs looking good, some suggestions below:

### Sample State
- Everything looks good here!

### Backend Routes
- [x] `GET /api/videos/:video_id/comments - return comments of the video` instead of a separate route for comments, we can grab the associated comments from a show route on our videos. This is because we only need those video's comments when we reach the video show page so can grab it all in one route.
- [x] for `likes`, if wanting to implement `dislike`, should add a boolean column in `likes` table of `is_unlike` that represents if the like is a `like` or a `dislike`. Then, you can have a POST and PATCH route that initially creates it based on the boolean and updates it if the user changes their mind. 

### Frontend Routes
- [x] there is a sidebar that youtube that can slide that you will want a separate component for.

Great work!

**Comment by nyan9** [comment]
Just made the suggested changes. Thanks, Rich!
